enum ArticleKey {
    PREFETCH_WEBWORKERS_REACT = "@mint/WEBWORKERS_PREFETCH_1",
    WEBAPP_PERFORMANCE = "@mint/WEBAPP_PERFORMANCE_1",
    LAZYLOADING_HTML_MEDIA = "@mint/HTML5_IMAGE_LAZY_LOADING",
    PATTERNS_TRY = "@mint/PATTERNS_TRY_1",
    ANECDOTE_GOTHAM_1 = "@mint/ANECDOTE_GOTHAM_1",
    ANECDOTE_COUCH_GAG_1 = "@mint/ANECDOTE_COUCHGAG_1",
    ESM_BROADCAST_CHANNEL_IMPORT_MAPS = "@mint/ESM_BROADCAST_CHANNEL_1",
    TC39_SIGNALS = "@mint/TC39_SIGNALS_1"
}

export default ArticleKey;