export const ERROR_CODES = {
  HTML: {
    READFILE_EXCEPTION: [1, 'FAILED TO LOAD TEMPLATE FILE FROM `html/index.html`']
  },
  STATIC_ASSETS: {
    PAGE_INDEXING_EXCEPTION: [2, 'FAILED TO INDEX PAGE-REGISTRY WITH REGISTRY-KEY.']
  },
  DYNAMIC_ASSETS: {
    PAGE_INDEXING_EXCEPTION: [2, 'FAILED TO INDEX PAGE-REGISTRY WITH REGISTRY-KEY.'],
    READ_MARKDOWN_FILE_EXCEPTION: [3, 'FAILED TO READ MARKDOWN FILE FROM PATH']
  }
} as const;
